# Test script
# Loads TwoSampleMR and all its dependency packages
library(TwoSampleMR)

packageVersion("TwoSampleMR")

# Imports packages (from TwoSampleMR DESCRIPTION file)
library(cowplot)
library(data.table)
library(dplyr)
library(ggplot2)
library(glmnet)
library(gridExtra)
library(gtable)
library(ieugwasr)
library(knitr)
library(lattice)
library(magrittr)
library(MASS)
library(MendelianRandomization)
library(meta)
library(mr.raps)
library(MRMix)
library(MRPRESSO)
library(pbapply)
library(plyr)
library(psych)
library(RadialMR)
library(reshape2)
library(rmarkdown)

# Suggests packages (from TwoSampleMR DESCRIPTION file)
library(Cairo)
library(car)
library(markdown)
library(MRInstruments)
library(randomForest)
library(testthat)

# Check finemapr loads
library(ggrepel)
library(finemapr)
